AWSTemplateFormatVersion: '2010-09-09'
Resources:
  lambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile:  !Sub |
          // inline
          exports.handler = function(event, context) {
          var responseData = {Message: 'Hello'};
          console.log(responseData);
          context.succeed('hello from testlambda04102019-214459')
          };

      FunctionName: 'testlambda04102019-214459'
      Handler: 'index.handler'
      Role:
        Fn::GetAtt:
          - lambdaRole
          - Arn
      Runtime: 'nodejs8.10'
  lambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'

        Version: '2012-10-17'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
